### ISSUE TITLE
How to invert scroll

### ISSUE THREAD

**Issue by Luca-Marantelli** [electerious/basicRotate#1]
Hi 
is it possible to invert horizontal scroll?

Now images rotates in the opposite direction of drag

Thanks

**Comment by electerious** [comment]
basicRotate uses the images inside your `div`. You can specify them in the opposite order to fix the scroll direction.

**Comment by Luca-Marantelli** [comment]
Hi

This is not a solution because we have images where the last one is the back part of, for example, a refrigerator. Inverting the order means that the first image user sees is this one

**Comment by electerious** [comment]
When the last image shows the back part it's probably a set of 180 degree images? I'm not sure how basicRotate works with those. When it's a set of 360 degree images you are able to start wherever you want.
